name: ❓ Question
description: Ask a question about CodeSearch
title: "[Question]: "
labels: ["question", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your question! 🤔

        Before submitting, please:
        - Check the [documentation](https://github.com/codesearch-ai/codesearch/tree/main/docs)
        - Search existing issues and discussions
        - Consider asking in [GitHub Discussions](https://github.com/codesearch-ai/codesearch/discussions) for general questions

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Please confirm the following
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: I have read the relevant documentation
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What type of question is this?
      options:
        - Installation & Setup
        - Configuration
        - Usage & API
        - Performance
        - Integration (MCP, VSCode)
        - Embedding Providers
        - Vector Databases
        - Troubleshooting
        - Best Practices
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: Please be as specific as possible...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context about your setup or use case
      placeholder: |
        - What are you trying to achieve?
        - What have you tried so far?
        - Any relevant configuration or code snippets?

  - type: textarea
    id: environment
    attributes:
      label: Environment (if relevant)
      description: Please provide information about your environment
      value: |
        - OS: [e.g. macOS 14.0, Ubuntu 22.04, Windows 11]
        - Node.js version: [e.g. 20.10.0]
        - Package version: [e.g. @codesearch/core@0.1.1]
        - Vector Database: [e.g. Qdrant local/cloud]
        - Embedding Provider: [e.g. OpenAI text-embedding-3-small]
